// Los datos de ejemplo de La Máquina de Obras: literales, sin aleatoriedad.
// Las fechas son relativas al día en que se ejecuta el seed, para que lo que se
// ve en pantalla siempre parezca de esta semana.
//
// Las cifras que salen en las diapositivas están cuadradas al céntimo. Cada
// presupuesto que participa en una de ellas lleva un `total` objetivo y dos
// líneas de ajuste: el seed calcula sus mediciones para clavar el importe.
import type { Dispositivo, Estado, Origen, Seccion, Unidad, Urgencia } from "@/lib/tipos";

export const EMPRESA = {
  nombre: "Reformas Soler",
  cif: "B66412907",
  direccion: "Carrer de Provença 233, 08008 Barcelona",
  telefono: "93 555 41 20",
  email: "hola@reformassoler.es",
  colorMarca: "#1B2537",
  ivaPct: 21,
  caducidadDias: 15,
  /** Días que hace que Manolo usa el sistema. Parte en dos las métricas. */
  diasDesdeAlta: 45,
  condiciones: [
    "Forma de pago: 40 % a la firma del presupuesto, 40 % a mitad de obra y 20 % a la entrega.",
    "Plazo orientativo de ejecución: entre 3 y 5 semanas desde el inicio, salvo imprevistos de obra o retrasos de suministro.",
    "No se incluyen licencias, tasas municipales ni permisos de la comunidad, que se gestionan aparte y se facturan a coste.",
    "No se incluyen los electrodomésticos ni los sanitarios que aporte el cliente.",
    "Los materiales de acabado están presupuestados en la gama indicada en cada partida; cualquier cambio se valora por escrito.",
    "Las mediciones son las tomadas en la visita; las diferencias en obra se regularizan al cierre.",
    "Este presupuesto es válido hasta la fecha indicada. Pasada esa fecha, los precios pueden variar.",
  ].join("\n"),
  seguimiento1:
    "Hola {cliente}, soy Manolo de Reformas Soler. Te escribo por el presupuesto de {obra} que te pasé hace unos días. ¿Has podido verlo con calma? Si tienes cualquier duda sobre las partidas o los plazos, dímelo y lo repasamos juntos sin compromiso.",
  seguimiento2:
    "Hola {cliente}, vuelvo a escribirte por el presupuesto de {obra} ({total}). ¿Os encajó el precio o preferís que lo ajustemos por fases? Muchas veces separando la obra en dos entregas sale mucho más llevadero. Dime qué te parece y lo vemos.",
  seguimiento3:
    "Hola {cliente}, te aviso de que el presupuesto de {obra} caduca en {dias}. A partir de esa fecha tendría que revisar los precios de material, que este año se mueven bastante. Si quieres que lo dejemos cerrado antes, avísame y lo preparo.",
};

export type ClienteSeed = {
  nombre: string;
  telefono: string;
  email: string;
  notas?: string;
};

export const CLIENTES: ClienteSeed[] = [
  { nombre: "María Gómez", telefono: "612 448 903", email: "maria.gomez@example.com", notas: "Piso del Eixample. Trabaja de mañanas: mejor llamar a partir de las 17 h." },
  { nombre: "Jordi Puig i Ferrer", telefono: "639 205 177", email: "jordi.puig@example.com", notas: "Vive de alquiler en el piso de al lado mientras dure la obra." },
  { nombre: "Núria Sallent", telefono: "677 310 452", email: "nuria.sallent@example.com" },
  { nombre: "Antonio Ramírez", telefono: "655 128 740", email: "antonio.ramirez@example.com", notas: "Cliente de siempre: ya le hicimos el aseo en su día." },
  { nombre: "Carme Vidal", telefono: "618 993 206", email: "carme.vidal@example.com" },
  { nombre: "Francisco Molina", telefono: "646 507 318", email: "francisco.molina@example.com" },
  { nombre: "Laia Bonet", telefono: "622 845 190", email: "laia.bonet@example.com", notas: "Pide factura a nombre de la comunidad." },
  { nombre: "Rosa Maria Clavé", telefono: "630 471 826", email: "rosa.clave@example.com" },
  { nombre: "Sergio Navarro", telefono: "671 302 558", email: "sergio.navarro@example.com" },
  { nombre: "Montse Riera", telefono: "608 736 214", email: "montse.riera@example.com" },
  { nombre: "Álvaro Castaño", telefono: "654 019 682", email: "alvaro.castano@example.com" },
  { nombre: "Elena Serrano", telefono: "627 553 041", email: "elena.serrano@example.com", notas: "Finca sin ascensor: contar bajada de escombros a mano." },
  { nombre: "Pere Colomer", telefono: "636 218 497", email: "pere.colomer@example.com" },
  { nombre: "Dolors Mas i Rovira", telefono: "649 604 173", email: "dolors.mas@example.com", notas: "Obra para su madre: baño adaptado, sin bañera." },
  { nombre: "Iván Peláez", telefono: "611 726 385", email: "ivan.pelaez@example.com" },
  { nombre: "Cristina Aymerich", telefono: "662 940 517", email: "cristina.aymerich@example.com" },
  { nombre: "Joaquín Herrera", telefono: "617 385 260", email: "joaquin.herrera@example.com" },
  { nombre: "Marta Sanchis", telefono: "623 178 904", email: "marta.sanchis@example.com" },
];

/** Una línea del presupuesto: código del banco y medición. */
export type LineaSeed = [codigo: string, medicion: number] | [codigo: string, medicion: number, marca: "opcional"];

/** Una línea que no está en el banco: amarilla y sin precio. */
export type AmarillaSeed = {
  capitulo: string;
  descripcion: string;
  unidad: Unidad;
  medicion: number;
  motivoIa: string;
};

export type AperturaSeed = {
  /** Días antes de hoy. 0 = hoy. */
  dias: number;
  /** Hora del día (Europe/Madrid) en la que se abrió. */
  hora: number;
  minuto?: number;
  visitaN: number;
  ciudad: string | null;
  pais?: string;
  dispositivo: Dispositivo;
  ip: string;
  /** Segundos leídos en cada sección. */
  secciones: [Seccion, number][];
};

export type PresupuestoSeed = {
  ref: string;
  cliente: number;
  titulo: string;
  direccion: string;
  estado: Estado;
  lineas: LineaSeed[];
  amarillas?: AmarillaSeed[];
  /**
   * Los dos códigos cuyas mediciones calcula el seed para clavar el total.
   * `bAprox` es la medición aproximada que se busca para el segundo, en
   * centésimas; la del primero sale de ahí.
   */
  ajuste?: { a: string; b: string; bAprox?: number };
  /** Total con IVA objetivo, en céntimos. */
  total?: number;
  /** Días antes de hoy en que se hizo la visita. */
  visita: number;
  /** Días entre la visita y el envío. Sin valor = todavía es borrador. */
  envio?: number;
  caducidad?: number;
  descuento?: number;
  /** Días antes de hoy en que se cerró (ganado, perdido o expirado). */
  cerrado?: number;
  motivo?: string;
  respuesta?: { texto: string; dias: number };
  aperturas?: AperturaSeed[];
  firma?: { dias: number; hora: number; ip: string; dispositivo: Dispositivo };
  /** El próximo seguimiento pendiente sale hoy (a la hora de DEMO_ALARMA). */
  alarma?: boolean;
};

const SECCIONES_LARGAS: [Seccion, number][] = [
  ["cabecera", 12],
  ["capitulos", 96],
  ["opcionales", 41],
  ["total", 68],
  ["condiciones", 24],
];
const SECCIONES_CORTAS: [Seccion, number][] = [
  ["cabecera", 8],
  ["capitulos", 34],
  ["total", 22],
];
const SECCIONES_MEDIAS: [Seccion, number][] = [
  ["cabecera", 10],
  ["capitulos", 62],
  ["total", 45],
  ["condiciones", 18],
];

export const PRESUPUESTOS: PresupuestoSeed[] = [
  /* ------------------------------------------------------------ borradores */
  {
    ref: "B1",
    cliente: 14,
    titulo: "Reforma de baño y aseo",
    direccion: "Carrer de Girona 118, 08009 Barcelona",
    estado: "borrador",
    visita: 1,
    lineas: [
      ["DEM-05", 2],
      ["DEM-01", 1],
      ["DEM-03", 46],
      ["DEM-04", 9],
      ["DEM-08", 1],
      ["ALB-06", 6],
      ["ALB-05", 1],
      ["ALB-07", 1],
      ["FON-01", 1],
      ["FON-03", 1],
      ["FON-05", 1],
      ["FON-06", 1],
      ["FON-08", 2],
      ["FON-09", 1],
      ["ELE-04", 2],
      ["ALI-01", 46],
      ["ALI-03", 9],
      ["CLI-02", 1, "opcional"],
    ],
    amarillas: [
      {
        capitulo: "Sin clasificar",
        descripcion: "Nicho de obra empotrado en la pared de la ducha, con led perimetral",
        unidad: "ud",
        medicion: 1,
        motivoIa: "No hay ninguna partida del banco que recoja un nicho de obra con iluminación",
      },
    ],
  },
  {
    ref: "B2",
    cliente: 17,
    titulo: "Cocina y office",
    direccion: "Avinguda Diagonal 402, 08037 Barcelona",
    estado: "borrador",
    visita: 0,
    lineas: [
      ["DEM-07", 1],
      ["DEM-03", 22],
      ["DEM-04", 14],
      ["DEM-08", 1],
      ["FON-13", 1],
      ["ELE-05", 1],
      ["ALI-01", 22],
      ["ALI-03", 14],
      ["COC-01", 6],
      ["COC-02", 6],
      ["COC-04", 1],
      ["COC-06", 1],
      ["COC-05", 4],
      ["GES-02", 1],
    ],
  },

  /* ------------------------ vivos sin respuesta desde hace más de 7 días */
  {
    ref: "V1",
    cliente: 3,
    titulo: "Reforma de cocina",
    direccion: "Carrer del Rosselló 271, 08008 Barcelona",
    estado: "visto",
    visita: 12,
    envio: 1,
    total: 1_080_000,
    ajuste: { a: "DEM-03", b: "PIN-01", bAprox: 1800 },
    lineas: [
      ["DEM-07", 1],
      ["DEM-04", 14],
      ["DEM-08", 1],
      ["ALB-07", 1],
      ["FON-13", 1],
      ["ELE-05", 1],
      ["ELE-03", 6],
      ["ALI-01", 20],
      ["ALI-03", 14],
      ["COC-01", 4],
      ["COC-03", 4],
      ["COC-04", 1],
      ["COC-05", 3],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 10, hora: 21, minuto: 14, visitaN: 1, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.112.7", secciones: SECCIONES_MEDIAS },
    ],
  },
  {
    ref: "V2",
    cliente: 5,
    titulo: "Baño principal y aseo de cortesía",
    direccion: "Passeig de Sant Joan 92, 08009 Barcelona",
    estado: "visto",
    visita: 14,
    envio: 1,
    total: 860_000,
    ajuste: { a: "DEM-03", b: "PIN-01", bAprox: 1400 },
    lineas: [
      ["DEM-05", 2],
      ["DEM-02", 1],
      ["DEM-04", 8],
      ["DEM-08", 1],
      ["ALB-06", 4],
      ["ALB-07", 1],
      ["FON-01", 1],
      ["FON-03", 1],
      ["FON-07", 2],
      ["FON-08", 2],
      ["ELE-04", 1],
      ["ALI-01", 18],
      ["ALI-03", 8],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 12, hora: 19, minuto: 42, visitaN: 1, ciudad: "Barcelona", dispositivo: "ordenador", ip: "212.170.44.19", secciones: SECCIONES_CORTAS },
    ],
  },
  {
    ref: "V3",
    cliente: 8,
    titulo: "Cambio de suelo y pintura",
    direccion: "Carrer de Sants 186, 08028 Barcelona",
    estado: "enviado",
    visita: 11,
    envio: 2,
    total: 620_000,
    ajuste: { a: "PIN-01", b: "CAR-05", bAprox: 2000 },
    lineas: [
      ["DEM-04", 42],
      ["DEM-08", 1],
      ["ALB-03", 42],
      ["ALI-06", 42],
      ["PIN-03", 4],
      ["GES-01", 1],
      ["GES-02", 1],
    ],
  },
  {
    ref: "V4",
    cliente: 12,
    titulo: "Reforma de baño",
    direccion: "Carrer Gran de Gràcia 149, 08012 Barcelona",
    estado: "visto",
    visita: 13,
    envio: 1,
    total: 560_000,
    ajuste: { a: "DEM-03", b: "PIN-01", bAprox: 850 },
    lineas: [
      ["DEM-05", 1],
      ["DEM-02", 1],
      ["DEM-04", 5],
      ["DEM-08", 1],
      ["ALB-06", 4],
      ["FON-01", 1],
      ["FON-03", 1],
      ["FON-06", 1],
      ["FON-08", 1],
      ["ELE-04", 1],
      ["ALI-03", 5],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 11, hora: 8, minuto: 27, visitaN: 1, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.201.88", secciones: SECCIONES_CORTAS },
    ],
  },

  /* ------------------------------------- vivos con actividad reciente */
  {
    ref: "W1",
    cliente: 0,
    titulo: "Reforma integral de baño",
    direccion: "Carrer de Mallorca 42, 08029 Barcelona",
    estado: "visto",
    visita: 2,
    envio: 0,
    total: 1_430_000,
    ajuste: { a: "DEM-03", b: "PIN-01", bAprox: 1000 },
    lineas: [
      ["DEM-05", 1],
      ["DEM-01", 1],
      ["DEM-04", 5],
      ["DEM-08", 1],
      ["ALB-06", 6],
      ["ALB-05", 1],
      ["ALB-07", 1],
      ["ALB-09", 5],
      ["FON-01", 1],
      ["FON-04", 1],
      ["FON-05", 1],
      ["FON-06", 1],
      ["FON-07", 1],
      ["FON-08", 1],
      ["FON-09", 1],
      ["FON-10", 1],
      ["ELE-04", 1],
      ["ELE-07", 6],
      ["ELE-08", 1],
      ["ALI-02", 33],
      ["ALI-04", 5],
      ["CLI-02", 1, "opcional"],
      ["GES-01", 1],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 1, hora: 22, minuto: 6, visitaN: 1, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.112.41", secciones: SECCIONES_MEDIAS },
      { dias: 0, hora: 9, minuto: 12, visitaN: 2, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.112.41", secciones: SECCIONES_LARGAS },
    ],
  },
  {
    ref: "W2",
    cliente: 1,
    titulo: "Reforma integral de piso",
    direccion: "Carrer de Balmes 214, 08006 Barcelona",
    estado: "en_conversacion",
    visita: 6,
    envio: 1,
    total: 1_240_000,
    ajuste: { a: "DEM-03", b: "PIN-01", bAprox: 2600 },
    lineas: [
      ["DEM-05", 1],
      ["DEM-01", 1],
      ["DEM-04", 55],
      ["DEM-10", 5],
      ["DEM-08", 2],
      ["ALB-03", 55],
      ["ALB-07", 1],
      ["FON-01", 1],
      ["ELE-06", 1],
      ["ELE-04", 1],
      ["ALI-06", 55],
      ["CAR-01", 4],
      ["GES-01", 1],
      ["GES-02", 1],
      ["CLI-01", 2, "opcional"],
    ],
    respuesta: {
      dias: 3,
      texto:
        "Buenos días Manolo. Nos gusta el presupuesto pero se nos va un poco de lo que teníamos pensado. ¿Habría forma de dejar la cocina para el año que viene y hacer ahora solo el baño y los suelos? Llámame cuando puedas.",
    },
    aperturas: [
      { dias: 4, hora: 20, minuto: 51, visitaN: 1, ciudad: "Barcelona", dispositivo: "ordenador", ip: "80.58.9.144", secciones: SECCIONES_LARGAS },
      { dias: 3, hora: 13, minuto: 5, visitaN: 2, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.66.10", secciones: SECCIONES_MEDIAS },
    ],
  },
  {
    ref: "W3",
    cliente: 2,
    titulo: "Cocina completa",
    direccion: "Carrer de la Indústria 77, 08025 Barcelona",
    estado: "visto",
    visita: 4,
    envio: 1,
    total: 820_000,
    alarma: true,
    ajuste: { a: "DEM-03", b: "PIN-01", bAprox: 900 },
    lineas: [
      ["DEM-07", 1],
      ["DEM-04", 12],
      ["DEM-08", 1],
      ["FON-13", 1],
      ["ELE-05", 1],
      ["ALI-01", 12],
      ["ALI-03", 12],
      ["COC-01", 3],
      ["COC-03", 3],
      ["COC-04", 1],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 0, hora: 11, minuto: 38, visitaN: 1, ciudad: "Sabadell", dispositivo: "ordenador", ip: "88.12.204.61", secciones: SECCIONES_MEDIAS },
    ],
  },
  {
    ref: "W4",
    cliente: 6,
    titulo: "Pintura integral del piso",
    direccion: "Carrer de Provença 388, 08025 Barcelona",
    estado: "enviado",
    visita: 1,
    envio: 0,
    total: 280_000,
    ajuste: { a: "PIN-01", b: "CAR-05", bAprox: 1200 },
    lineas: [
      ["PIN-02", 60],
      ["PIN-03", 4],
      ["PIN-04", 3],
      ["GES-01", 1],
      ["GES-02", 1],
    ],
  },
  {
    ref: "W5",
    cliente: 9,
    titulo: "Baño completo",
    direccion: "Carrer del Comerç 31, 08003 Barcelona",
    estado: "visto",
    visita: 7,
    envio: 1,
    total: 570_000,
    ajuste: { a: "DEM-03", b: "PIN-01", bAprox: 900 },
    lineas: [
      ["DEM-05", 1],
      ["DEM-02", 1],
      ["DEM-04", 5],
      ["DEM-08", 1],
      ["ALB-06", 4],
      ["ALB-07", 1],
      ["FON-01", 1],
      ["FON-03", 1],
      ["FON-06", 1],
      ["FON-08", 1],
      ["ELE-04", 1],
      ["ALI-03", 5],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 2, hora: 18, minuto: 3, visitaN: 1, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.130.12", secciones: SECCIONES_MEDIAS },
    ],
  },
  {
    ref: "W6",
    cliente: 11,
    titulo: "Cambio de ventanas",
    direccion: "Carrer de Muntaner 305, 08021 Barcelona",
    estado: "enviado",
    visita: 6,
    envio: 2,
    total: 240_000,
    ajuste: { a: "PIN-01", b: "CAR-05", bAprox: 1000 },
    lineas: [
      ["CAR-04", 2],
      ["DEM-09", 1],
      ["ALB-02", 6],
      ["GES-04", 1],
    ],
  },
  {
    ref: "W7",
    cliente: 4,
    titulo: "Reforma de cocina",
    direccion: "Carrer de Sardenya 140, 08013 Barcelona",
    estado: "en_conversacion",
    visita: 10,
    envio: 1,
    total: 630_000,
    ajuste: { a: "DEM-03", b: "PIN-01", bAprox: 900 },
    lineas: [
      ["DEM-07", 1],
      ["DEM-04", 10],
      ["DEM-08", 1],
      ["FON-13", 1],
      ["ELE-05", 1],
      ["ALI-01", 8],
      ["ALI-03", 10],
      ["COC-01", 2],
      ["COC-03", 2],
      ["GES-02", 1],
    ],
    respuesta: {
      dias: 6,
      texto:
        "Hola, gracias por el presupuesto. Mi marido pregunta si la encimera de laminado se puede cambiar por la de cuarzo y cuánto subiría. Por lo demás lo vemos bien.",
    },
    aperturas: [
      { dias: 8, hora: 12, minuto: 22, visitaN: 1, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.77.203", secciones: SECCIONES_MEDIAS },
      { dias: 6, hora: 19, minuto: 9, visitaN: 2, ciudad: "Barcelona", dispositivo: "ordenador", ip: "80.58.31.7", secciones: SECCIONES_LARGAS },
    ],
  },
  {
    ref: "W8",
    cliente: 16,
    titulo: "Suelo de todo el piso",
    direccion: "Carrer de Còrsega 512, 08025 Barcelona",
    estado: "visto",
    visita: 9,
    envio: 1,
    total: 410_000,
    ajuste: { a: "PIN-01", b: "CAR-05", bAprox: 1500 },
    lineas: [
      ["DEM-04", 30],
      ["DEM-08", 1],
      ["ALB-03", 30],
      ["ALI-06", 30],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 5, hora: 17, minuto: 45, visitaN: 1, ciudad: "Barcelona", dispositivo: "tablet", ip: "83.45.19.60", secciones: SECCIONES_CORTAS },
    ],
  },

  /* --------------------------------------- ganados en los últimos 30 días */
  {
    ref: "G1",
    cliente: 7,
    titulo: "Reforma integral de baño y cocina",
    direccion: "Carrer de Rocafort 96, 08015 Barcelona",
    estado: "ganado",
    visita: 13,
    envio: 1,
    cerrado: 6,
    total: 1_470_000,
    ajuste: { a: "DEM-03", b: "PIN-01", bAprox: 1200 },
    lineas: [
      ["DEM-05", 1],
      ["DEM-01", 1],
      ["DEM-07", 1],
      ["DEM-04", 16],
      ["DEM-08", 2],
      ["ALB-06", 5],
      ["ALB-05", 1],
      ["ALB-07", 1],
      ["FON-01", 1],
      ["FON-13", 1],
      ["FON-03", 1],
      ["FON-08", 1],
      ["FON-09", 1],
      ["ELE-04", 1],
      ["ELE-05", 1],
      ["ALI-01", 26],
      ["ALI-03", 16],
      ["COC-01", 2],
      ["COC-03", 2],
      ["COC-04", 1],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 11, hora: 21, minuto: 30, visitaN: 1, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.90.22", secciones: SECCIONES_LARGAS },
      { dias: 7, hora: 10, minuto: 14, visitaN: 2, ciudad: "Barcelona", dispositivo: "ordenador", ip: "80.58.77.31", secciones: SECCIONES_MEDIAS },
      { dias: 6, hora: 18, minuto: 51, visitaN: 3, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.90.22", secciones: SECCIONES_LARGAS },
    ],
    firma: { dias: 6, hora: 19, ip: "83.45.90.22", dispositivo: "movil" },
  },
  {
    ref: "G2",
    cliente: 10,
    titulo: "Reforma de cocina y salón",
    direccion: "Avinguda de Madrid 145, 08028 Barcelona",
    estado: "ganado",
    visita: 21,
    envio: 1,
    cerrado: 11,
    total: 930_000,
    ajuste: { a: "DEM-03", b: "PIN-01", bAprox: 2200 },
    lineas: [
      ["DEM-07", 1],
      ["DEM-04", 30],
      ["DEM-08", 1],
      ["ALB-03", 30],
      ["FON-13", 1],
      ["ELE-05", 1],
      ["ALI-01", 10],
      ["ALI-06", 30],
      ["COC-01", 2],
      ["COC-03", 3],
      ["COC-04", 1],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 19, hora: 20, minuto: 2, visitaN: 1, ciudad: "Barcelona", dispositivo: "ordenador", ip: "80.58.120.9", secciones: SECCIONES_LARGAS },
      { dias: 12, hora: 9, minuto: 41, visitaN: 2, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.55.8", secciones: SECCIONES_MEDIAS },
    ],
    firma: { dias: 11, hora: 12, ip: "80.58.120.9", dispositivo: "ordenador" },
  },
  {
    ref: "G3",
    cliente: 13,
    titulo: "Baño adaptado sin bañera",
    direccion: "Carrer Major 24, 08172 Sant Cugat del Vallès",
    estado: "ganado",
    visita: 29,
    envio: 2,
    cerrado: 18,
    total: 490_000,
    ajuste: { a: "DEM-03", b: "PIN-01", bAprox: 800 },
    lineas: [
      ["DEM-05", 1],
      ["DEM-01", 1],
      ["DEM-04", 5],
      ["DEM-08", 1],
      ["ALB-06", 4],
      ["FON-01", 1],
      ["FON-04", 1],
      ["FON-08", 1],
      ["ELE-04", 1],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 26, hora: 18, minuto: 12, visitaN: 1, ciudad: "Sant Cugat del Vallès", dispositivo: "movil", ip: "83.47.11.90", secciones: SECCIONES_LARGAS },
      { dias: 19, hora: 11, minuto: 7, visitaN: 2, ciudad: "Sant Cugat del Vallès", dispositivo: "movil", ip: "83.47.11.90", secciones: SECCIONES_MEDIAS },
    ],
    firma: { dias: 18, hora: 17, ip: "83.47.11.90", dispositivo: "movil" },
  },

  /* ------------------------------ ganados fuera de la ventana de 30 días */
  {
    ref: "G4",
    cliente: 15,
    titulo: "Pintura y suelo del piso",
    direccion: "Carrer de Cartagena 289, 08025 Barcelona",
    estado: "ganado",
    visita: 44,
    envio: 1,
    cerrado: 36,
    lineas: [
      ["DEM-04", 58],
      ["DEM-08", 1],
      ["ALB-03", 58],
      ["ALI-06", 58],
      ["CAR-05", 62],
      ["PIN-01", 184],
      ["PIN-03", 5],
      ["GES-01", 1],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 42, hora: 19, minuto: 22, visitaN: 1, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.208.4", secciones: SECCIONES_MEDIAS },
    ],
    firma: { dias: 36, hora: 20, ip: "83.45.208.4", dispositivo: "movil" },
  },
  {
    ref: "G5",
    cliente: 3,
    titulo: "Reforma de aseo",
    direccion: "Carrer de Sepúlveda 61, 08015 Barcelona",
    estado: "ganado",
    visita: 90,
    envio: 14,
    cerrado: 61,
    lineas: [
      ["DEM-05", 1],
      ["DEM-03", 18],
      ["DEM-04", 4],
      ["DEM-08", 1],
      ["ALB-07", 1],
      ["FON-02", 2],
      ["FON-07", 1],
      ["FON-08", 1],
      ["ELE-04", 1],
      ["ALI-01", 18],
      ["ALI-03", 4],
      ["PIN-01", 12],
      ["GES-02", 1],
    ],
    firma: { dias: 61, hora: 13, ip: "83.45.11.202", dispositivo: "ordenador" },
  },

  /* ------------------------------------------------ perdidos tras el alta */
  {
    ref: "P1",
    cliente: 2,
    titulo: "Reforma de baño",
    direccion: "Carrer de Tarragona 108, 08015 Barcelona",
    estado: "perdido",
    visita: 38,
    envio: 0,
    cerrado: 30,
    motivo: "El cliente ha aceptado otro presupuesto",
    lineas: [
      ["DEM-05", 1],
      ["DEM-02", 1],
      ["DEM-03", 26],
      ["DEM-04", 6],
      ["DEM-08", 1],
      ["ALB-06", 4],
      ["FON-01", 1],
      ["FON-03", 1],
      ["FON-08", 1],
      ["ALI-01", 26],
      ["ALI-03", 6],
      ["PIN-01", 14],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 36, hora: 21, minuto: 11, visitaN: 1, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.140.77", secciones: SECCIONES_CORTAS },
    ],
  },
  {
    ref: "P2",
    cliente: 5,
    titulo: "Cocina completa",
    direccion: "Carrer d'Aragó 455, 08013 Barcelona",
    estado: "perdido",
    visita: 34,
    envio: 1,
    cerrado: 26,
    motivo: "Precio por encima de lo que esperaba",
    lineas: [
      ["DEM-07", 1],
      ["DEM-03", 20],
      ["DEM-04", 12],
      ["DEM-08", 1],
      ["FON-13", 1],
      ["ELE-05", 1],
      ["ALI-01", 20],
      ["ALI-03", 12],
      ["COC-01", 6],
      ["COC-02", 6],
      ["COC-04", 1],
      ["COC-06", 1],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 32, hora: 13, minuto: 40, visitaN: 1, ciudad: "Barcelona", dispositivo: "ordenador", ip: "80.58.55.19", secciones: SECCIONES_MEDIAS },
    ],
  },
  {
    ref: "P3",
    cliente: 9,
    titulo: "Pintura del piso",
    direccion: "Carrer de Bailèn 92, 08009 Barcelona",
    estado: "perdido",
    visita: 30,
    envio: 1,
    cerrado: 22,
    motivo: "Aplazan la obra a después del verano",
    lineas: [
      ["PIN-01", 210],
      ["PIN-03", 6],
      ["PIN-04", 5],
      ["GES-01", 1],
      ["GES-02", 1],
    ],
  },
  {
    ref: "P4",
    cliente: 11,
    titulo: "Reforma integral",
    direccion: "Rambla de Catalunya 77, 08007 Barcelona",
    estado: "perdido",
    visita: 27,
    envio: 2,
    cerrado: 14,
    motivo: "Sin respuesta del cliente",
    lineas: [
      ["DEM-05", 1],
      ["DEM-01", 1],
      ["DEM-07", 1],
      ["DEM-03", 60],
      ["DEM-04", 95],
      ["DEM-09", 8],
      ["DEM-08", 3],
      ["ALB-03", 95],
      ["ALB-04", 60],
      ["ALB-07", 1],
      ["FON-01", 1],
      ["FON-13", 1],
      ["ELE-06", 1],
      ["ALI-03", 95],
      ["ALI-01", 60],
      ["CAR-01", 7],
      ["COC-01", 6],
      ["COC-02", 6],
      ["PIN-01", 240],
      ["GES-03", 1],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 24, hora: 20, minuto: 33, visitaN: 1, ciudad: "Barcelona", dispositivo: "ordenador", ip: "80.58.201.5", secciones: SECCIONES_LARGAS },
    ],
  },
  {
    ref: "P5",
    cliente: 14,
    titulo: "Baño y aseo",
    direccion: "Carrer de Lepant 233, 08013 Barcelona",
    estado: "perdido",
    visita: 24,
    envio: 1,
    cerrado: 16,
    motivo: "Precio: pedían bajar un 20 %",
    lineas: [
      ["DEM-05", 2],
      ["DEM-01", 1],
      ["DEM-03", 40],
      ["DEM-04", 10],
      ["DEM-08", 1],
      ["ALB-06", 5],
      ["FON-01", 1],
      ["FON-03", 1],
      ["FON-08", 2],
      ["FON-09", 1],
      ["ELE-04", 2],
      ["ALI-01", 40],
      ["ALI-03", 10],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 22, hora: 18, minuto: 55, visitaN: 1, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.166.30", secciones: SECCIONES_MEDIAS },
    ],
  },
  {
    ref: "P6",
    cliente: 1,
    titulo: "Cambio de suelo",
    direccion: "Carrer de Calàbria 154, 08015 Barcelona",
    estado: "perdido",
    visita: 21,
    envio: 1,
    cerrado: 12,
    motivo: "El cliente ha aceptado otro presupuesto",
    lineas: [
      ["DEM-04", 52],
      ["DEM-08", 1],
      ["ALB-03", 52],
      ["ALI-07", 52],
      ["CAR-05", 54],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 19, hora: 12, minuto: 18, visitaN: 1, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.3.140", secciones: SECCIONES_CORTAS },
    ],
  },
  {
    ref: "P7",
    cliente: 16,
    titulo: "Cocina y office",
    direccion: "Carrer de Nàpols 190, 08013 Barcelona",
    estado: "perdido",
    visita: 19,
    envio: 0,
    cerrado: 10,
    motivo: "Aplazan la obra",
    lineas: [
      ["DEM-07", 1],
      ["DEM-03", 18],
      ["DEM-04", 15],
      ["DEM-08", 1],
      ["FON-13", 1],
      ["ELE-05", 1],
      ["ALI-01", 18],
      ["ALI-03", 15],
      ["COC-01", 5],
      ["COC-03", 5],
      ["COC-04", 1],
      ["GES-02", 1],
    ],
  },
  {
    ref: "P8",
    cliente: 6,
    titulo: "Reforma de baño",
    direccion: "Carrer de Viladomat 88, 08015 Barcelona",
    estado: "perdido",
    visita: 16,
    envio: 1,
    cerrado: 8,
    motivo: "Precio",
    lineas: [
      ["DEM-05", 1],
      ["DEM-01", 1],
      ["DEM-03", 30],
      ["DEM-04", 6],
      ["DEM-08", 1],
      ["ALB-06", 5],
      ["ALB-05", 1],
      ["FON-01", 1],
      ["FON-04", 1],
      ["FON-05", 1],
      ["FON-08", 1],
      ["FON-09", 1],
      ["ELE-04", 1],
      ["ALI-02", 30],
      ["ALI-04", 6],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 14, hora: 21, minuto: 2, visitaN: 1, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.99.11", secciones: SECCIONES_MEDIAS },
    ],
  },
  {
    ref: "P9",
    cliente: 12,
    titulo: "Ventanas y persianas",
    direccion: "Carrer de Dos de Maig 271, 08025 Barcelona",
    estado: "perdido",
    visita: 13,
    envio: 1,
    cerrado: 5,
    motivo: "Otro presupuesto más barato",
    lineas: [
      ["CAR-04", 7],
      ["DEM-09", 2],
      ["ALB-02", 16],
      ["PIN-01", 30],
      ["GES-04", 1],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 11, hora: 19, minuto: 27, visitaN: 1, ciudad: "Barcelona", dispositivo: "ordenador", ip: "80.58.14.72", secciones: SECCIONES_CORTAS },
    ],
  },
  {
    ref: "P10",
    cliente: 17,
    titulo: "Pintura y alisado de gotelé",
    direccion: "Carrer de Padilla 320, 08025 Barcelona",
    estado: "perdido",
    visita: 10,
    envio: 1,
    cerrado: 3,
    motivo: "Sin respuesta del cliente",
    lineas: [
      ["PIN-02", 124],
      ["PIN-03", 5],
      ["GES-01", 1],
      ["GES-02", 1],
    ],
  },

  /* ----------------------------------------------- expirados tras el alta */
  {
    ref: "E1",
    cliente: 4,
    titulo: "Reforma de cocina",
    direccion: "Carrer d'Entença 121, 08015 Barcelona",
    estado: "expirado",
    visita: 40,
    envio: 2,
    lineas: [
      ["DEM-07", 1],
      ["DEM-03", 16],
      ["DEM-04", 11],
      ["DEM-08", 1],
      ["FON-13", 1],
      ["ELE-05", 1],
      ["ALI-01", 16],
      ["ALI-03", 11],
      ["COC-01", 4],
      ["COC-03", 4],
      ["COC-04", 1],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 36, hora: 20, minuto: 44, visitaN: 1, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.222.18", secciones: SECCIONES_CORTAS },
    ],
  },
  {
    ref: "E2",
    cliente: 8,
    titulo: "Baño completo",
    direccion: "Carrer de la Marina 204, 08013 Barcelona",
    estado: "expirado",
    visita: 26,
    envio: 1,
    lineas: [
      ["DEM-05", 1],
      ["DEM-01", 1],
      ["DEM-03", 28],
      ["DEM-04", 5],
      ["DEM-08", 1],
      ["ALB-06", 4],
      ["ALB-05", 1],
      ["FON-01", 1],
      ["FON-03", 1],
      ["FON-05", 1],
      ["FON-08", 1],
      ["FON-09", 1],
      ["ELE-04", 1],
      ["ALI-01", 28],
      ["ALI-03", 5],
      ["PIN-01", 11],
      ["GES-02", 1],
    ],
    aperturas: [
      { dias: 24, hora: 19, minuto: 6, visitaN: 1, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.70.19", secciones: SECCIONES_MEDIAS },
      { dias: 2, hora: 22, minuto: 47, visitaN: 2, ciudad: "Barcelona", dispositivo: "movil", ip: "83.45.70.19", secciones: SECCIONES_LARGAS },
    ],
  },
  {
    ref: "E3",
    cliente: 13,
    titulo: "Suelo y pintura del piso",
    direccion: "Carrer de Rogent 45, 08026 Barcelona",
    estado: "expirado",
    visita: 18,
    envio: 0,
    lineas: [
      ["DEM-04", 46],
      ["DEM-08", 1],
      ["ALB-03", 46],
      ["ALI-06", 46],
      ["CAR-05", 48],
      ["PIN-01", 132],
      ["GES-02", 1],
    ],
  },

  /* ------------------------------ antes del alta: el historial importado */
  {
    ref: "A1",
    cliente: 0,
    titulo: "Aseo de cortesía",
    direccion: "Carrer de Villarroel 178, 08036 Barcelona",
    estado: "expirado",
    visita: 79,
    envio: 14,
    lineas: [
      ["DEM-05", 1],
      ["DEM-03", 14],
      ["DEM-04", 3],
      ["DEM-08", 1],
      ["FON-02", 2],
      ["FON-07", 1],
      ["FON-08", 1],
      ["ELE-04", 1],
      ["ALI-01", 14],
      ["ALI-03", 3],
      ["PIN-01", 9],
    ],
  },
  {
    ref: "A2",
    cliente: 7,
    titulo: "Reforma de baño",
    direccion: "Carrer de Provença 12, 08029 Barcelona",
    estado: "perdido",
    visita: 78,
    envio: 12,
    cerrado: 52,
    motivo: "Precio",
    lineas: [
      ["DEM-05", 1],
      ["DEM-01", 1],
      ["DEM-03", 27],
      ["DEM-04", 6],
      ["DEM-08", 1],
      ["ALB-06", 4],
      ["FON-01", 1],
      ["FON-03", 1],
      ["FON-08", 1],
      ["FON-09", 1],
      ["ALI-01", 27],
      ["ALI-03", 6],
      ["GES-02", 1],
    ],
  },
  {
    ref: "A3",
    cliente: 10,
    titulo: "Cocina",
    direccion: "Carrer del Consell de Cent 402, 08013 Barcelona",
    estado: "perdido",
    visita: 72,
    envio: 13,
    cerrado: 47,
    motivo: "Aplazan la obra",
    lineas: [
      ["DEM-07", 1],
      ["DEM-03", 17],
      ["DEM-04", 10],
      ["DEM-08", 1],
      ["FON-13", 1],
      ["ELE-05", 1],
      ["ALI-01", 17],
      ["ALI-03", 10],
      ["COC-01", 5],
      ["COC-03", 5],
      ["COC-04", 1],
    ],
  },
  {
    ref: "A4",
    cliente: 15,
    titulo: "Pintura del piso",
    direccion: "Carrer de Marià Cubí 63, 08006 Barcelona",
    estado: "perdido",
    visita: 82,
    envio: 15,
    cerrado: 55,
    motivo: "Sin respuesta del cliente",
    lineas: [
      ["PIN-01", 168],
      ["PIN-03", 5],
      ["GES-02", 1],
    ],
  },
  {
    ref: "A5",
    cliente: 16,
    titulo: "Suelo del salón",
    direccion: "Carrer de Berlín 41, 08014 Barcelona",
    estado: "perdido",
    visita: 85,
    envio: 16,
    cerrado: 58,
    motivo: "El cliente ha aceptado otro presupuesto",
    lineas: [
      ["DEM-04", 32],
      ["DEM-08", 1],
      ["ALB-03", 32],
      ["ALI-06", 32],
      ["CAR-05", 26],
    ],
  },
];

/* ------------------------------------------------------------ solicitudes */

export type SolicitudSeed = {
  clienteNombre: string;
  telefono: string | null;
  email: string | null;
  direccion: string;
  titulo: string;
  urgencia: Urgencia;
  textoOriginal: string;
  conceptos: { descripcion: string; medicion: number | null; unidad: Unidad | null; notas: string | null }[];
  /** Horas antes de ahora en que entró la solicitud. */
  horas: number;
  /** «manolo» (dictada tras la visita) o «cliente» (llegó por la web). Por defecto, «manolo». */
  origen?: Origen;
};

export const SOLICITUDES: SolicitudSeed[] = [
  {
    clienteNombre: "Rosa Maria Clavé",
    telefono: "630 471 826",
    email: null,
    direccion: "Carrer de Aribau 155, 08036 Barcelona",
    titulo: "Pintura integral de piso de 90 m²",
    urgencia: "media",
    horas: 5,
    textoOriginal:
      "Piso de Aribau 155, tercero segunda, unos noventa metros. La señora quiere pintar todo el piso, paredes y techos, hay gotelé en el pasillo y en los dos dormitorios, eso habría que alisarlo. Son unos cuarenta metros de gotelé más o menos. Cuatro puertas para esmaltar y tres radiadores. Quiere que se lo hagamos en agosto que se van de vacaciones, hay que proteger los muebles porque no vacían el piso. Limpieza final incluida.",
    conceptos: [
      { descripcion: "Pintura plástica en paredes y techos de todo el piso", medicion: 90, unidad: "m2", notas: "Dos manos, color a elegir" },
      { descripcion: "Alisado de gotelé en pasillo y dos dormitorios", medicion: 40, unidad: "m2", notas: null },
      { descripcion: "Esmaltado de puertas", medicion: 4, unidad: "ud", notas: null },
      { descripcion: "Pintado de radiadores", medicion: 3, unidad: "ud", notas: null },
      { descripcion: "Protección de muebles, no vacían el piso", medicion: 1, unidad: "pa", notas: "La obra sería en agosto" },
      { descripcion: "Limpieza final de obra", medicion: 1, unidad: "pa", notas: null },
    ],
  },
  {
    clienteNombre: "Sergio Navarro",
    telefono: "671 302 558",
    email: "sergio.navarro@example.com",
    direccion: "Carrer de Loreto 42, 08029 Barcelona",
    titulo: "Cocina completa con isla",
    urgencia: "alta",
    horas: 2,
    textoOriginal:
      "Cocina de Loreto 42. Hay que tirar todos los muebles de cocina que hay y el alicatado, son unos dieciocho metros de pared. El suelo también fuera, catorce metros. Quieren muebles nuevos, cinco metros lineales de mueble bajo y alto, encimera de cuarzo, y una isla pequeña de metro y medio. Fregadero bajo encimera, campana, y montar la placa, el horno y el lavavajillas que los compran ellos. Instalación de fontanería nueva y la eléctrica de la cocina también, que es de los años setenta. Corre prisa porque se mudan en octubre.",
    conceptos: [
      { descripcion: "Desmontaje del mobiliario de cocina existente", medicion: 1, unidad: "ud", notas: null },
      { descripcion: "Picado de alicatado de la cocina", medicion: 18, unidad: "m2", notas: null },
      { descripcion: "Picado de solado", medicion: 14, unidad: "m2", notas: null },
      { descripcion: "Alicatado nuevo", medicion: 18, unidad: "m2", notas: "Gama media" },
      { descripcion: "Solado nuevo", medicion: 14, unidad: "m2", notas: null },
      { descripcion: "Mobiliario de cocina bajo y alto", medicion: 5, unidad: "ml", notas: null },
      { descripcion: "Encimera de cuarzo", medicion: 5, unidad: "ml", notas: null },
      { descripcion: "Isla de cocina de metro y medio", medicion: 1.5, unidad: "ml", notas: "No estaba en el banco de precios" },
      { descripcion: "Fregadero bajo encimera con grifería", medicion: 1, unidad: "ud", notas: null },
      { descripcion: "Campana extractora", medicion: 1, unidad: "ud", notas: null },
      { descripcion: "Instalación de electrodomésticos: placa, horno y lavavajillas", medicion: 3, unidad: "ud", notas: "Los aporta el cliente" },
      { descripcion: "Renovación de la instalación de fontanería de cocina", medicion: 1, unidad: "ud", notas: null },
      { descripcion: "Renovación de la instalación eléctrica de cocina", medicion: 1, unidad: "ud", notas: "La actual es de los años setenta" },
    ],
  },
  {
    clienteNombre: "Marta Ruiz",
    telefono: "622 418 903",
    email: "marta.ruiz@example.com",
    direccion: "Carrer de Verdi 71, 08012 Barcelona",
    titulo: "Reforma de baño",
    urgencia: "media",
    horas: 1,
    origen: "cliente",
    textoOriginal:
      "Hola, queremos reformar el baño de casa. Es pequeño y tiene bañera: nos gustaría cambiarla por un plato de ducha, poner azulejos nuevos y cambiar el lavabo y el váter. ¿Podríais venir a verlo alguna tarde entre semana? Gracias.",
    conceptos: [],
  },
];

/* ------------------------------------------------------------- plantillas */

export type PlantillaSeed = {
  nombre: string;
  descripcion: string;
  lineas: LineaSeed[];
};

export const PLANTILLAS: PlantillaSeed[] = [
  {
    nombre: "Baño completo",
    descripcion: "Baño de 4 a 5 m² con ducha, gama media. Demolición, instalaciones, alicatado y sanitarios.",
    lineas: [
      ["DEM-05", 1],
      ["DEM-01", 1],
      ["DEM-03", 28],
      ["DEM-04", 5],
      ["DEM-08", 1],
      ["ALB-06", 5],
      ["ALB-05", 1],
      ["ALB-07", 1],
      ["FON-01", 1],
      ["FON-03", 1],
      ["FON-05", 1],
      ["FON-06", 1],
      ["FON-07", 1],
      ["FON-08", 1],
      ["FON-09", 1],
      ["FON-10", 1],
      ["ELE-04", 1],
      ["ELE-08", 1],
      ["ALI-01", 28],
      ["ALI-03", 5],
      ["CLI-02", 1, "opcional"],
      ["GES-02", 1],
    ],
  },
  {
    nombre: "Cocina completa",
    descripcion: "Cocina de 10 a 14 m²: desmontaje, instalaciones nuevas, alicatado, solado y mobiliario con encimera de cuarzo.",
    lineas: [
      ["DEM-07", 1],
      ["DEM-03", 20],
      ["DEM-04", 12],
      ["DEM-08", 1],
      ["ALB-07", 1],
      ["FON-13", 1],
      ["ELE-05", 1],
      ["ELE-03", 6],
      ["ALI-01", 20],
      ["ALI-03", 12],
      ["COC-01", 5],
      ["COC-02", 5],
      ["COC-04", 1],
      ["COC-06", 1],
      ["COC-05", 3],
      ["GES-02", 1],
    ],
  },
  {
    nombre: "Pintura integral",
    descripcion: "Piso de unos 90 m²: pintura plástica en paredes y techos, esmaltado de puertas y protección.",
    lineas: [
      ["PIN-01", 210],
      ["PIN-03", 5],
      ["PIN-04", 4],
      ["GES-01", 1],
      ["GES-02", 1],
    ],
  },
];
